### ISSUE TITLE
Fail to open document with Microsoft Office (Office 10)

### ISSUE THREAD

**Issue by ray241278** [Tichau/FileConverter#155]
Hello,

i want to convert Excel (XLSX) to PDF. I am using Office 2010 and it is activated. Unfortunately, I keep getting the error message: Fail to open document with Microsoft Office (check if your license / installation are valid).

I have now completely uninstalled Office 2010 and reinstalled it. Then also the file converter. Unfortunately I still get this error message.

I would be very happy if you could help me.

Thanks in advance
Rainer Heck

**Comment by ambition88** [comment]
I meet the same trouble.
![image](https://user-images.githubusercontent.com/62361824/113812391-9ed12400-97a0-11eb-951e-6a26ed6d9c7c.png)

**Comment by CBest3** [comment]
我也是一样的问题，为office2021版
![image](https://user-images.githubusercontent.com/49545064/121984434-86dfd700-cdc5-11eb-9c01-cc3e26a6902f.png)

**Comment by controlb** [comment]
I get the same issue using File Converter in converting Word .docx files to pdf. The error appears to be HRESULT: 0x80029C4A TYPE-E-CANTLOADLIBRARY

This is a relatively recent issue. Also, Word itself has no problem creating PDFs natively.

![Screenshot 2021-09-19 130359](https://user-images.githubusercontent.com/1575991/133926835-7b07feb6-deba-48ef-a638-65c29e47eb0c.png)

**Comment by Martin67776** [comment]
Same here
<img width="704" alt="image" src="https://github.com/Tichau/FileConverter/assets/99792836/91764a64-dc41-48ed-9199-f2f7c9455f81">

**Comment by DBY749** [comment]
same
<img width="394" alt="image" src="https://github.com/Tichau/FileConverter/assets/69231890/0e7e649d-36c3-41fa-bb71-0afdb82e08b0">

**Comment by 1z1y** [comment]
![image](https://github.com/Tichau/FileConverter/assets/92145805/2c4f149f-df1d-4b15-8524-fba6e87475fe)
same with you

**Comment by 1z1y** [comment]
> same 相同 <img alt="image" width="394" height="15.5" src="https://user-images.githubusercontent.com/69231890/249425513-0e7e649d-36c3-41fa-bb71-0afdb82e08b0.png">

I tried to install the x64 but it didn't work; then I used x86 version, it worked

**Comment by nagybarna1** [comment]
Hello All, 

I've the same problem. Office is activated and pdf can be generated from word in native.

Log file:
Instantiate word application via interop.
System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.Word.ApplicationClass' to interface type 'Microsoft.Office.Interop.Word._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00020970-0000-0000-C000-000000000046}' failed due to the following error: Hiba típustár/DLL betöltésekor. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Word.ApplicationClass.set_Visible(Boolean prop)
   at FileConverter.ConversionJobs.ConversionJob_Word.InitializeOfficeApplicationInstanceIfNecessary()
   at FileConverter.ConversionJobs.ConversionJob_Word.TryLoadDocumentIfNecessary()
Failed to initialize office application.
Fail: Fail to open document with Microsoft Office (check if your licence/installation are valid).
Conversion Failed.

![image](https://github.com/Tichau/FileConverter/assets/153604383/19f0d1db-3eac-439f-b438-c5d08a3fb4a0)

Anyone any solution or idea how to fix that issue?

Thank you

**Comment by Tichau** [comment]
File Converter is only compatible from Office 2013 and later. 
I should put a feedback to explain the needed version.

**Comment by 3Gsleepless** [comment]
我卸载wps，解决了无法使用microsoft office文档的问题
