### ISSUE TITLE
Fail: Fail to open document with Microsoft Office - pdf not generated

### ISSUE THREAD

**Issue by nagybarna1** [Tichau/FileConverter#350]
Hello All,

I've an issue with pdf generation from doc/docx files, however I've licensed and activate MS office installation in my PC.

In the log file I can see below error:

Tuesday, December 12, 2023 10:06:46 AM

Convert file C:\Konferenciaszervező\MiniCRM\PDF_generálás_kredit__tansi_kikuldes\Tanusitvany minta_11.23_Alapitvanyok.doc to C:\Konferenciaszervező\MiniCRM\PDF_generálás_kredit__tansi_kikuldes\Tanusitvany minta_11.23_Alapitvanyok.pdf.
Instantiate word application via interop.
System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.Word.ApplicationClass' to interface type 'Microsoft.Office.Interop.Word._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00020970-0000-0000-C000-000000000046}' failed due to the following error: Hiba típustár/DLL betöltésekor. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Word.ApplicationClass.set_Visible(Boolean prop)
   at FileConverter.ConversionJobs.ConversionJob_Word.InitializeOfficeApplicationInstanceIfNecessary()
   at FileConverter.ConversionJobs.ConversionJob_Word.TryLoadDocumentIfNecessary()
Failed to initialize office application.
Fail: Fail to open document with Microsoft Office (check if your licence/installation are valid).
Conversion Failed.

![image](https://github.com/Tichau/FileConverter/assets/153604383/e9e5e1ac-f461-4e92-9f87-ccb74a4f9e8e)
[Diagnostics-10h6m46s.zip](https://github.com/Tichau/FileConverter/files/13646171/Diagnostics-10h6m46s.zip)
[FileConverter_reg_user_files.zip](https://github.com/Tichau/FileConverter/files/13646175/FileConverter_reg_user_files.zip)

Can you please check what cause the issue and advise?

Thank You,
Barnabas

**Comment by superpink617** [comment]
I encountered the same problem and don't know what happened!Fail to open document with Microsoft Office（check if your licence/installation are valid）

**Comment by Tichau** [comment]
Hello,
What are your version of Office ? File Converter is only compatible with Office 2013 and later.

**Comment by nagybarna1** [comment]
Hello All,

My office version is office 2019 professional plus, so I'm sure that the
problem is different.
Any advise?

Thanks and Regards,
Barnabas

Adrien Allard ***@***.***> ezt írta (időpont: 2024. jan. 19.,
P, 19:53):

**Comment by Tichau** [comment]
Can you send me your log files just after failing a conversion ?

You can follow the step here: https://github.com/Tichau/FileConverter/wiki/Troubleshooting

**Comment by RaidOpe** [comment]
I think it would be helpful

[Unable to cast COM object of Office Interop Word](https://learn.microsoft.com/en-us/archive/msdn-technet-forums/d34c4f78-46f3-478e-9c44-95ea8461e46f)

**Comment by superpink617** [comment]
我解决了 但我忘了之前是如何解决的? 隐约记得是写在了office365

**Comment by nagybarna1** [comment]
Hello Adrien,

Sure, it's still not woring for me.
I've MS Office 2019 Pro license installed on my laptop (official one).

Please find logs and other files attached to check.

[image: image.png]

Let me know if you have any advice.

Thanks and Regards,
Barnabás

Adrien Allard ***@***.***> ezt írta (időpont: 2024. jan. 28.,
V, 18:28):

**Comment by 3Gsleepless** [comment]
我卸载了wps，然后尝试excel转pdf和doc转pdf，解决了Microsoft Office许可证的问题
