### ISSUE TITLE
Error: "fail to open document with microsoft office (check if your licence/installation are valid)"

### ISSUE THREAD

**Issue by Hyp3r64** [Tichau/FileConverter#368]
https://drive.google.com/drive/folders/1rVDGY9WXQcwc-OsedeBAfstfxnYjfJvo?usp=sharing

all the required files and screenshots are on my drive. follow the link ^^^

My windows and MS office software is activated, but File Converter is still showing this error. 
I tried re-installing, but didn't work.

**Comment by OPADILOP** [comment]
Can you tell me the Word version 
Maybe I could help

**Comment by Hyp3r64** [comment]
Version 2401 (Build 17231.20236)

**Comment by itz-rj-here** [comment]
Is your license genuine or fake license?
like kmspico license?

**Comment by Hyp3r64** [comment]
i am using a student account provided by my university. it was working just fine for the past year. I recently reinstalled windows, this issue appeared after that.

my windows isn't genuine though.

**Comment by Tichau** [comment]
Hello,
Thanks for your report (complete with all diagnostics and screenshots <3)

I put here the error that happened (that i've read in the diag)
```
System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.Word.ApplicationClass' to interface type 'Microsoft.Office.Interop.Word._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00020970-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Word.ApplicationClass.set_Visible(Boolean prop)
   at FileConverter.ConversionJobs.ConversionJob_Word.InitializeOfficeApplicationInstanceIfNecessary()
   at FileConverter.ConversionJobs.ConversionJob_Word.TryLoadDocumentIfNecessary()
Failed to initialize office application.
Fail: Fail to open document with Microsoft Office (check if your licence/installation are valid).
```

The interop Microsoft library seems to not find any version of Word. Keep in mind that File Converter is only compatible with Word >= 2013, but I assume that your version is more recent ^^.

You can try to reinstall word, maybe it will be detected better. I honnestly don't know what I can do since this code is not on FileConverter side.

**Comment by marc-frank** [comment]
I have the same issue. It was working fine for a lot of years. Now I bought Office 365. Then I tried to convert a document again, which didn't work. Updated FileConverter from 1.2.3 to 2.0.2. No change. I had to install Office from their website, as doing so from the Microsoft Store didn't work.

**Comment by FranckMorinNBK** [comment]
Same issue here. 
I have used file converted for a few months only but it worked very well to batch-convert word file to pdf. 
I have a genuine Office 2019 installed and did not change anything lately but now I get an error.
I use file converter 2.0.2 

```
Instantiate word application via interop.
System.InvalidCastException: Impossible d'effectuer un cast d'un objet COM de type 'Microsoft.Office.Interop.Word.ApplicationClass' en type d'interface 'Microsoft.Office.Interop.Word._Application'. Cette opération a échoué, car l'appel QueryInterface sur le composant COM pour l'interface avec l'IID '{00020970-0000-0000-C000-000000000046}' a échoué en raison de l'erreur suivante : Élément introuvable. (Exception de HRESULT : 0x8002802B (TYPE_E_ELEMENTNOTFOUND)).
   à System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   à Microsoft.Office.Interop.Word.ApplicationClass.set_Visible(Boolean prop)
   à FileConverter.ConversionJobs.ConversionJob_Word.InitializeOfficeApplicationInstanceIfNecessary()
   à FileConverter.ConversionJobs.ConversionJob_Word.TryLoadDocumentIfNecessary()
Failed to initialize office application.
Fail: Impossible d'ouvrir le document avec Microsoft Office (vérifiez que la licence/l'installation sont valides).
Conversion Failed.
```

**Comment by Scorpvs** [comment]
Same error for me:
Regolar Office license too
ystem.InvalidCastException: Impossibile eseguire il cast di oggetti COM di tipo 'Microsoft.Office.Interop.Word.ApplicationClass' in tipi di interfaccia 'Microsoft.Office.Interop.Word._Application'. L'operazione non è stata completata perché la chiamata QueryInterface sul componente COM per l'interfaccia con IID '{00020970-0000-0000-C000-000000000046}' non è riuscita a causa del seguente errore: Errore durante il caricamento della libreria DLL dei tipi. (Eccezione da HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
